### PR TITLE
Ft google auth

### PR DESCRIPTION
**Pull request by zanderthuo**
Handle Google authentication and console.log the details on success.
 Write tests for Google authentication.
 Handle Facebook authentication and console.log the details on success.
 Write tests for Facebook authentication
 Host the frontend app on Heroku

### CODE REVIEW

**Review by Dave-mash — DISMISSED** [review]
Great work Alexander.

**Review by Jordan-type — DISMISSED** [review]

**Review by Dave-mash — APPROVED** [review]

**Review by Jordan-type — APPROVED** [review]
Great work

**Review by Njeri-Marg — APPROVED** [review]
Kudos

**Comment by zanderthuo** [comment]
Handle Google authentication and console.log the details on success.
Write tests for Google authentication.
Handle Facebook authentication and console.log the details on success.
Write tests for Facebook authentication
Host the frontend app on Heroku

**Pull request merged**
