### PR TITLE
Ft farmers dashboard page

### LINKED ISSUE #11: Build the remaining static pages
**Tasks**
- [x] Market place page.
- [x] Build the cart page.
- [ ] Build a checkout page.
- [ ] Build a product item page.
- [x] Build a user account profile.
- [x] Build a vendor account profile.
- [x] Setup testing with jest.

### PR DESCRIPTION
**Pull request by Dave-mash**
**What does pull request do?**
Builds a farmers dashboard page

**How do I test this?**
https://buildforsdgcohort2.github.io/Team-254-zaoBora-frontend/#/farmer/profile

### CODE REVIEW

**Review by zanderthuo — DISMISSED** [review]
Great work

**Comment by Njeri-Marg** [comment]
Nice work

**Comment by Njeri-Marg** [comment]
Nice work

**Review by Njeri-Marg — DISMISSED** [review]

**Review by Jordan-type — DISMISSED** [review]

**Comment by Jordan-type** [comment]
resolve the yarn.lock file

**Pull request merged**
